project_id = "cownjkcmzseyddqejiim"

[functions.enhance-text]
verify_jwt = false

[functions.generate-doodle]
verify_jwt = false

[functions.generate-story]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.suggest-music]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false
